FROM php:apache@sha256:441142e8df7419b18af74fa7a2472e55ad4e6fa4599a989ad38f58029d314464
#RUN apt update && apt install -y msmtp
#RUN a2enmod rewrite
#COPY ./uploads.ini /usr/local/etc/php/conf.d/uploads.ini
#COPY msmtprc /etc/msmtprc